[build]
  # Run the Next.js build command
  command = "npm run build"
  # The publish directory for the production build.
  # For Next.js, you typically deploy the output built by @netlify/plugin-nextjs.
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[[plugins]]
  # This plugin bundles your Next.js app properly for Netlify
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase the build timeout to allow for longer builds
  node_bundler = "esbuild"
  external_node_modules = ["@node-rs/*"]